common_packages:
  - curl
  - wget
  - vim
  - htop
  - git
  - ufw
  - python3-pip
  - ntp
deploy_user: deploy
deploy_user_groups: deploy
ssh_port: 22
deploy_ssh_key: ""
ssh_disable_root: true
ssh_password_auth: false
timezone: "Europe/Moscow"