# Ansible Inventory для Linux контейнеров
# Сгенерирован автоматически

[linux_containers]
linux-container-3 ansible_connection=docker
linux-container-2 ansible_connection=docker
linux-container-1 ansible_connection=docker

[linux_containers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[webservers]
linux-container-1 ansible_connection=docker

[appservers]
linux-container-2 ansible_connection=docker

[databases]
linux-container-3 ansible_connection=docker